<a href="https://colab.research.google.com/github/Parsahm86/pytorch_learning/blob/main/00_Pytorch_Fundamentals/00_Pytorch_Fundamentals_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals — پایه‌های PyTorch

**English:** A structured beginner-friendly notebook covering the fundamental PyTorch tensor operations used in Machine Learning and Deep Learning.

**فارسی:** این نوت‌بوک یک جمع‌بندی ساختاریافته از مباحث پایه‌ی PyTorch است؛ با تمرکز روی Tensorها، ابعاد، dtype، indexing، تغییر شکل، NumPy و GPU.

> **Goal / هدف:** بعد از این نوت‌بوک باید بتوانی Tensorهای PyTorch را بسازی، مشخصات آن‌ها را بررسی کنی، روی آن‌ها عملیات انجام دهی و بین CPU / GPU / NumPy جابه‌جا شوی.


## 0. Setup & Imports — آماده‌سازی

**English:** Import the main libraries and optionally check whether an NVIDIA GPU is available.

**فارسی:** کتابخانه‌های اصلی را وارد می‌کنیم و در صورت نیاز بررسی می‌کنیم که آیا GPU انویدیا در دسترس است یا نه.


In [1]:
# import os
# os.system('nvidia-smi')

import torch as t
import numpy as np

print(f"PyTorch version: {t.__version__}")


PyTorch version: 2.11.0+cpu


## 1. Scalars, Vectors, Matrices & Tensors — اسکالر، بردار، ماتریس و تنسور

**English:** A Tensor is PyTorch's main data structure. Its number of dimensions is available through `.ndim`, while `.shape` describes the size of each dimension.

**فارسی:** Tensor ساختار اصلی داده در PyTorch است. ویژگی `.ndim` تعداد ابعاد را نشان می‌دهد و `.shape` اندازه‌ی هر بُعد را مشخص می‌کند.

- Scalar → 0D
- Vector → 1D
- Matrix → 2D
- Tensor → usually 3D or higher


In [2]:
# Scalar — اسکالر
scalar = t.tensor(7)
print("Scalar:", scalar)
print("Value:", scalar.item())
print("ndim:", scalar.ndim)

# Vector — بردار
vector = t.tensor([1, 2])
print("\nVector:", vector)
print("ndim:", vector.ndim)
print("shape:", vector.shape)

# Matrix — ماتریس
matrix = t.tensor([[1, 2],
                    [3, 4]])
print("\nMatrix:\n", matrix)
print("ndim:", matrix.ndim)
print("shape:", matrix.shape)

# Tensor — تنسور سه‌بعدی
tensor = t.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

print("\nTensor:\n", tensor)
print("ndim:", tensor.ndim)
print("shape:", tensor.shape)
print("tensor[1,1,1]:", tensor[1, 1, 1])
print("tensor[1,1,0]:", tensor[1, 1, 0])
print("tensor[1:, :, 1:]:\n", tensor[1:, :, 1:])


Scalar: tensor(7)
Value: 7
ndim: 0

Vector: tensor([1, 2])
ndim: 1
shape: torch.Size([2])

Matrix:
 tensor([[1, 2],
        [3, 4]])
ndim: 2
shape: torch.Size([2, 2])

Tensor:
 tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
ndim: 3
shape: torch.Size([3, 2, 2])
tensor[1,1,1]: tensor(8)
tensor[1,1,0]: tensor(7)
tensor[1:, :, 1:]:
 tensor([[[ 6],
         [ 8]],

        [[10],
         [12]]])


## 2. Random, Zeros, Ones & Arange — ساخت Tensorهای رایج

**English:** PyTorch provides convenient functions for creating tensors filled with random values, zeros, ones, or a sequence of numbers.

**فارسی:** PyTorch توابع آماده‌ای برای ساخت Tensorهای تصادفی، صفر، یک و دنباله‌ای در اختیار ما می‌گذارد.


In [3]:
# Random Tensor — تنسور تصادفی
random_tensor = t.rand(5, 10, 5)
print("Random tensor shape:", random_tensor.shape)

random_tensor_size = t.rand(size=(3, 255, 255))
print("Random tensor:", random_tensor_size.shape)
print("ndim:", random_tensor_size.ndim)

# Zeros Tensor — تنسور صفر
zeros_tensor = t.zeros(size=(2, 3, 3))
print("\nZeros tensor:\n", zeros_tensor)

# Ones Tensor — تنسور یک
ones_tensor = t.ones(size=(2, 3, 3))
print("\nOnes tensor:\n", ones_tensor)

# Arange — دنباله
one_to_ten = t.arange(start=1, end=11)
print("\nArange:", one_to_ten)

# Zeros Like — همان shape و dtype، اما پر از صفر
ten_zeros = t.zeros_like(one_to_ten)
print("Zeros like:", ten_zeros)


Random tensor shape: torch.Size([5, 10, 5])
Random tensor: torch.Size([3, 255, 255])
ndim: 3

Zeros tensor:
 tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

Ones tensor:
 tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

Arange: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Zeros like: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


## 3. Tensor dtypes — انواع داده

**English:** Tensor operations depend on data type (`dtype`). Common types include `torch.float32`, `torch.float64`, `torch.int32`, and `torch.int64`.

**فارسی:** هر Tensor یک نوع داده (`dtype`) دارد. در Deep Learning معمولاً `float32` بسیار رایج است.

**Important:** The dtype of a tensor can affect memory usage, numerical precision, and compatibility with operations/models.


In [4]:
tensor_int32 = t.tensor(
    [[1.0, 2.0],
     [3.0, 4.0]],
    dtype=t.int32,
    device=None,
    requires_grad=False
)

print("Tensor:")
print(tensor_int32)
print("dtype:", tensor_int32.dtype)

tensor_int64 = tensor_int32.type(t.int64)
print("\nConverted dtype:", tensor_int64.dtype)

mul_t32_t64 = tensor_int64 * tensor_int32
print("\nResult:")
print(mul_t32_t64)
print("Result dtype:", mul_t32_t64.dtype)


Tensor:
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
dtype: torch.int32

Converted dtype: torch.int64

Result:
tensor([[ 1,  4],
        [ 9, 16]])
Result dtype: torch.int64


## 4. Tensor Attributes — بررسی مشخصات Tensor

**English:** Three properties you should become comfortable with are:

- `.dtype` → data type
- `.device` → CPU or CUDA device
- `.shape` / `.size()` → dimensions and their sizes

**فارسی:** این سه مورد را در کار روزمره با PyTorch زیاد استفاده خواهی کرد.


In [5]:
some_tensor = t.rand(3, 4, dtype=t.float16)

print(some_tensor)
print(f"\nData type: {some_tensor.dtype}")
print(f"Device: {some_tensor.device}")
print(f"Shape: {some_tensor.shape}")
print(f"Size: {some_tensor.size()}")


tensor([[0.4014, 0.2539, 0.4658, 0.7534],
        [0.5234, 0.4258, 0.1567, 0.7881],
        [0.0327, 0.2979, 0.8857, 0.0928]], dtype=torch.float16)

Data type: torch.float16
Device: cpu
Shape: torch.Size([3, 4])
Size: torch.Size([3, 4])


## 5. Min, Max, Argmin & Argmax — کمینه، بیشینه و محل آن‌ها

**English:** `min()` and `max()` return values. `argmin()` and `argmax()` return the index of the minimum/maximum value.

**فارسی:** تفاوت مهم این است که `min/max` مقدار را می‌دهند، اما `argmin/argmax` موقعیت آن مقدار را برمی‌گردانند.


In [6]:
tensor = t.arange(0, 100, 8)

print("Tensor:", tensor)
print("Max value:", t.max(tensor))
print("Min value:", t.min(tensor))
print("Index of max:", t.argmax(tensor))
print("Index of min:", t.argmin(tensor))


Tensor: tensor([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96])
Max value: tensor(96)
Min value: tensor(0)
Index of max: tensor(12)
Index of min: tensor(0)


## 6. Reshape — تغییر شکل Tensor

**English:** `.reshape()` changes the shape while preserving the number of elements.

**فارسی:** در `reshape` تعداد کل عناصر باید ثابت بماند. مثلاً یک Tensor با 10 عنصر می‌تواند به شکل `(1,10)`، `(10,1)` یا `(2,5)` تبدیل شود.


In [7]:
tensor = t.arange(1, 11)
print("Original:", tensor, tensor.shape)

tensor_reshaped = tensor.reshape(1, 10)
print("\n(1,10):", tensor_reshaped)

tensor_reshaped2 = tensor.reshape(10, 1)
print("\n(10,1):", tensor_reshaped2)

tensor_reshaped3 = tensor.reshape(2, 5)
print("\n(2,5):", tensor_reshaped3)


Original: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) torch.Size([10])

(1,10): tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

(10,1): tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

(2,5): tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


## 7. View — ساخت View از Tensor

**English:** `.view()` creates a view that shares the same underlying memory when possible. Therefore, changing the view can change the original Tensor.

**فارسی:** `view` در حالت معمول یک Tensor جدید با حافظه‌ی جدا نمی‌سازد؛ View و Tensor اصلی می‌توانند حافظه‌ی مشترک داشته باشند. بنابراین تغییر View ممکن است Tensor اصلی را هم تغییر دهد.

> **Key idea:** `view` is closely related to memory layout/contiguity, so it is worth learning this concept carefully later.


In [8]:
x = t.arange(1, 11)
z = x.view(1, 10)

print("x:", x)
print("z:", z)

# Change z
z[:, 0] = 5

print("\nAfter changing z:")
print("z:", z)
print("x:", x)


x: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
z: tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

After changing z:
z: tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
x: tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])


## 8. Stack — روی هم قرار دادن Tensorها

**English:** `torch.stack()` combines tensors by creating a **new dimension**. The `dim` argument controls where that new dimension is inserted.

**فارسی:** `stack` یک بُعد جدید ایجاد می‌کند. مقدار `dim` تعیین می‌کند این بُعد جدید کجا قرار بگیرد.

> **Note:** `stack` is different from `cat`; `cat` concatenates along an existing dimension, while `stack` creates a new one.


In [9]:
x = t.arange(1, 11)

print("x:", x)
print("x shape:", x.shape)

x_stacked = t.stack([x, x, x, x], dim=1)

print("\nStacked:")
print(x_stacked)
print("Shape:", x_stacked.shape)


x: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
x shape: torch.Size([10])

Stacked:
tensor([[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])
Shape: torch.Size([10, 4])


## 9. Squeeze & Unsqueeze — حذف و اضافه کردن بُعد 1

**English:**
- `squeeze()` removes dimensions whose size is `1`.
- `unsqueeze(dim)` inserts a new dimension of size `1`.

**فارسی:** این دو تابع برای کنترل shape، مخصوصاً هنگام آماده‌سازی داده برای مدل‌های PyTorch، بسیار مهم هستند.


In [10]:
tensor_reshaped = t.arange(1, 11).reshape(1, 10)

print("Original:")
print(tensor_reshaped)
print("Shape:", tensor_reshaped.shape)

tensor_squeezed = tensor_reshaped.squeeze()

print("\nSqueezed:")
print(tensor_squeezed)
print("Shape:", tensor_squeezed.shape)

tensor_unsqueezed = tensor_squeezed.unsqueeze(dim=0)

print("\nUnsqueezed:")
print(tensor_unsqueezed)
print("Shape:", tensor_unsqueezed.shape)


Original:
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
Shape: torch.Size([1, 10])

Squeezed:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Shape: torch.Size([10])

Unsqueezed:
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
Shape: torch.Size([1, 10])


## 10. Permute — جابه‌جایی ترتیب ابعاد

**English:** `.permute()` rearranges the dimensions of a Tensor according to the specified order.

For an image represented as `(height, width, channels)`, we can convert it to `(channels, height, width)`.

**فارسی:** `permute` ترتیب محورهای Tensor را عوض می‌کند؛ خود مفهوم داده تغییر نمی‌کند، اما ترتیب ابعاد تغییر می‌کند.

This is especially important when working with image data.


In [11]:
# Image-like tensor: [height, width, channels]
x_original = t.rand(size=(224, 224, 3))

print("Original shape:", x_original.shape)

# Rearrange: [H, W, C] -> [C, H, W]
x_permute = x_original.permute(2, 0, 1)

print("Permuted shape:", x_permute.shape)


Original shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


## 11. Indexing — دسترسی به عناصر Tensor

**English:** Tensor indexing follows the dimension order. For a tensor shaped `(1, 3, 3)`, three indices can be used to select an element.

**فارسی:** در Tensor چندبعدی، هر index مربوط به یک dimension است. این موضوع را باید برای کار با batch، channel و image data خوب یاد بگیری.


In [12]:
x_original = t.arange(1, 10).reshape(1, 3, 3)

print(x_original)
print("Shape:", x_original.shape)

print("\nx_original[0, :, 1]:")
print(x_original[0, :, 1])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape: torch.Size([1, 3, 3])

x_original[0, :, 1]:
tensor([2, 5, 8])


## 12. NumPy ↔ PyTorch — تبدیل بین NumPy و Tensor

**English:** PyTorch can convert NumPy arrays to tensors and tensors to NumPy arrays.

**Important:** CPU tensors and NumPy arrays can share memory in common cases. GPU tensors cannot be directly converted to NumPy; move them to CPU first.

**فارسی:** برای تبدیل Tensor روی GPU به NumPy باید ابتدا آن را به CPU برگردانیم، چون NumPy روی CPU کار می‌کند.

Typical pattern:

`GPU Tensor → .cpu() → .numpy()`


In [13]:
# NumPy array -> PyTorch Tensor
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor_from_numpy = t.from_numpy(array)

print("NumPy array:", array)
print("NumPy dtype:", array.dtype)
print("\nPyTorch tensor:", tensor_from_numpy)
print("Tensor dtype:", tensor_from_numpy.dtype)

# PyTorch Tensor -> NumPy
tensor1 = t.ones(8)
tensor_numpy = tensor1.numpy()

print("\nPyTorch tensor:", tensor1)
print("Tensor dtype:", tensor1.dtype)
print("\nNumPy array:", tensor_numpy)
print("NumPy dtype:", tensor_numpy.dtype)


NumPy array: [1 2 3 4 5 6 7 8 9]
NumPy dtype: int64

PyTorch tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Tensor dtype: torch.int64

PyTorch tensor: tensor([1., 1., 1., 1., 1., 1., 1., 1.])
Tensor dtype: torch.float32

NumPy array: [1. 1. 1. 1. 1. 1. 1. 1.]
NumPy dtype: float32


### NumPy dtype note — نکته درباره dtype

**English:** `torch.from_numpy()` preserves the NumPy array's dtype. Therefore, if your NumPy array is `float64`, the resulting Tensor will normally also be `torch.float64`.

**فارسی:** `from_numpy` نوع داده‌ی آرایه NumPy را حفظ می‌کند؛ بنابراین باید همیشه به `dtype` توجه داشته باشی.


## 13. Random Seeds — کنترل تصادفی‌بودن

**English:** Setting a random seed makes random operations reproducible.

**فارسی:** وقتی seed یکسان باشد و شرایط یکسان باشد، می‌توانیم نتایج تصادفی قابل تکرار داشته باشیم. برای آزمایش‌ها و Debugging این موضوع بسیار مهم است.


In [14]:
random_seed = 42

t.manual_seed(random_seed)
random_tensor_A = t.rand(3, 3)

t.manual_seed(random_seed)
random_tensor_B = t.rand(3, 3)

print("Tensor A:\n", random_tensor_A)
print("\nTensor B:\n", random_tensor_B)

print("\nA == B:")
print(random_tensor_A == random_tensor_B)


Tensor A:
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

Tensor B:
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

A == B:
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## 14. Device-Agnostic Code — اجرای کد روی CPU یا GPU

**English:** A common PyTorch pattern is to select CUDA when available and otherwise use CPU.

**فارسی:** این روش باعث می‌شود کد ما هم روی سیستم دارای GPU و هم روی سیستم فقط با CPU اجرا شود.

```python
device = 'cuda' if torch.cuda.is_available() else 'cpu'
```

After selecting the device, tensors/models can be moved with `.to(device)`.


In [15]:
device = 'cuda' if t.cuda.is_available() else 'cpu'

print("Selected device:", device)

tensor = t.tensor([1, 2, 3])
print("Original:", tensor)
print("Original device:", tensor.device)

tensor_on_device = tensor.to(device)

print("\nTensor on selected device:", tensor_on_device)
print("Device:", tensor_on_device.device)


Selected device: cpu
Original: tensor([1, 2, 3])
Original device: cpu

Tensor on selected device: tensor([1, 2, 3])
Device: cpu


## 15. GPU → CPU → NumPy — مسیر تبدیل

**English:** If a Tensor is on a CUDA device, use `.cpu()` before calling `.numpy()`.

**فارسی:** الگوی مهم:

**CUDA Tensor → CPU Tensor → NumPy Array**

```python
tensor_on_cpu = tensor_on_device.cpu()
numpy_array = tensor_on_cpu.numpy()
```

If the Tensor is already on CPU, `.cpu()` is harmless and keeps the code simple.


In [16]:
# Safe conversion pattern:
tensor_back_on_cpu = tensor_on_device.cpu()
tensor_numpy = tensor_back_on_cpu.numpy()

print("CPU tensor:", tensor_back_on_cpu)
print("NumPy array:", tensor_numpy)


CPU tensor: tensor([1, 2, 3])
NumPy array: [1 2 3]


# Quick Reference — خلاصه‌ی دستورات مهم

| Operation | PyTorch |
|---|---|
| Create Tensor | `torch.tensor()` |
| Random Tensor | `torch.rand()` |
| Zeros | `torch.zeros()` |
| Ones | `torch.ones()` |
| Sequence | `torch.arange()` |
| Same shape | `torch.zeros_like()` |
| Number of dimensions | `.ndim` |
| Shape | `.shape` |
| Size | `.size()` |
| Reshape | `.reshape()` |
| View | `.view()` |
| Stack | `torch.stack()` |
| Remove dim=1 | `.squeeze()` |
| Add dim=1 | `.unsqueeze()` |
| Rearrange dimensions | `.permute()` |
| Maximum | `torch.max()` |
| Minimum | `torch.min()` |
| Index of max | `torch.argmax()` |
| Index of min | `torch.argmin()` |
| NumPy → Tensor | `torch.from_numpy()` |
| Tensor → NumPy | `.numpy()` |
| CPU/GPU transfer | `.to(device)` |
| GPU → CPU | `.cpu()` |
| Check CUDA | `torch.cuda.is_available()` |
| Reproducibility | `torch.manual_seed()` |
